"""empty message

Revision ID: 75c436cedef8
Revises: f73a1b89efa0
Create Date: 2025-02-02 11:38:28.633485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '75c436cedef8'
down_revision: Union[str, None] = 'f73a1b89efa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_category_field', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.drop_column('category_field')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('bank_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('bank_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('bank_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('bank_type')
        batch_op.drop_column('bank_status')
        batch_op.drop_column('bank_category')
        batch_op.drop_column('original_description')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_field', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('bank_category_field')

    # ### end Alembic commands ###
