"""empty message

Revision ID: e16c63b7eceb
Revises: f1794cb49d3c
Create Date: 2025-02-19 18:58:44.581105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e16c63b7eceb'
down_revision: Union[str, None] = 'f1794cb49d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('gross_amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_amount', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
